config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "legends#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: :show
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :legends, only: %i[index show new create destroy]
  resources :reservations do
    member do
      patch :update_status
    end
  end
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/legend.rb
class Legend < ApplicationRecord
  belongs_to :user
  has_many :reservations, dependent: :destroy
  has_many_attached :photos
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :legend
  belongs_to :user
  enum status: { pending: 0, confirmed: 1, canceled: 2, declined: 3 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :legends
  has_many :reservations, dependent: :destroy
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/legends_controller.rb
class LegendsController < ApplicationController
  before_action :set_legend, only: [:show]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @legends = Legend.all
    if params[:query].present?
      sql_subquery = "name ILIKE :query OR category ILIKE :query"
      @legends = @legends.where(sql_subquery, query: "%#{params[:query]}%")
    end
  end

  def show
    @legend = Legend.find(params[:id])
    @reservation = Reservation.new
  end

  def new
    @legend = Legend.new
  end

  def create
    @legend = Legend.new(legend_params)
    @legend.user = current_user
    if @legend.save
      redirect_to @legend, notice: 'Legend was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @legend = Legend.find(params[:id])
    @legend.destroy
    redirect_to user_path(current_user), status: :see_other
  end

  private

  def set_legend
    @legend = Legend.find(params[:id])
  end

  def legend_params
    params.require(:legend).permit(:name, :description, :category, :price, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @reservations = Reservation.all
  end

  def new
    @reservation = Reservation.new()
  end

  def show
    @reservation = Reservation.find(params[:id])
  end

  def create
    @reservation = Reservation.new(reservation_params)
    @reservation.user = current_user
    # @reservation.status = "Pending"
    if @reservation.save
      redirect_to @reservation.legend, notice: 'La réservation a bien été prise en compte.'
    elsif user_signed_in?
      # si l utilisateur est connecte + NOTICE reservation failed
      # RESTER vers legend show
      render 'legends/show', notice: 'La réservation a échouée.'
    else
      # sinon redirection vers page de connection
      redirect_to new_user_session_path, notice: "Merci de vous connecté avant d'éffectuer une réservation."
    end
  end

  def update_status
    @reservation = Reservation.find(params[:id])
    if @reservation.update(status: params[:reservation][:status])
      flash[:notice] = "Le statut de la réservation a bien été mis à jour à : #{params[:reservation][:status]} ."
    else
      flash[:alert] = 'Une erreur est survenue lors de la mise à jour du statut.'
    end
    redirect_back(fallback_location: @reservation.legend)
  end

  private

  def reservation_params
    params.require(:reservation).permit(:starting_date, :ending_date, :legend_id, :status)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_params
  before_action :access_dashboard

  def show
    # et un user
    set_params
    # la méthode show doit passer un array de réservation
    @reservations = @user.reservations # ça donne toutes les réservations EMISES par @user
    # un array de legendes à la vue
    @legends = @user.legends
  end

  def access_dashboard
    set_params
    if @user == current_user
      # Passe la show automatiquement
    else
      redirect_to legends_path
    end
  end

  def set_params
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LegendaryObjects</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/legends/_form.html.erb
<%= simple_form_for(legend) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :price %>
  <% categories = ['Armes', 'Vêtements-Chaussures', 'Bijoux & accessoires ', 'Moyen de transport'] %>
  <%= f.input :category, as: :select, collection: categories %>
  <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  <%= f.submit %>
<% end %>

app/views/legends/index.html.erb
<div class="search-bar-container">
  <%= render "shared/search_bar" %>
</div>

<% if @legends == [] %>
  <div class="messages-search">
  <p>Désolé, aucun objet de légende ne correspond à votre recherche.</p>
  <p>Essayez à nouveau.</p>
</div>
<% else %>
  <div class="legends-index-main-container">
    <div class="legends-index-cards-container">
      <% @legends.each do |legend| %>
        <%= link_to legend_path(legend), class: "legends-index-card-single" do %>
          <div class="legends-index-img-div">
            <%= cl_image_tag legend.photos.last.key, height: 250, width: 250 %>
          </div>
          <div class="legends-index-card-single-infos">
            <h2><%= legend.name %></h2>
            <p>
              <%= legend.category %> <br>
              <%= legend.price %> €/jour
            </p>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/legends/new.html.erb
<h1 class= "modification-titre-add"> Mettez votre objet sur Legendary Object</h1>

<div id="object_card">
<%= simple_form_for(@legend) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :price %>
  <% categories = ['Armes', 'Vêtements-Chaussures', 'Bijoux & accessoires ', 'Moyen de transport'] %>
  <%= f.input :category, as: :select, collection: categories %>
  <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  <%= f.submit %>

<% end %>
</div>

app/views/legends/show.html.erb
<div>
  <%= render "shared/search_bar" %>
</div>

<div class="main-container">
  <div class="card_object">
      <div class="card_info">
        <h2><%= @legend.name %> </h2>
      </div>
    <div class="card_image">
      <%= cl_image_tag @legend.photos.last.key, class: "image" %>
    </div>

<%# redimensionner les images des cards %>

 <div class="card_info">
      <div class="cards_2_trips">
        <p><%= @legend.description %></p>
        <br>
        <p><%= @legend.category  %> </p>
        <p><%= @legend.price %> €/jour</p>
      </div>
      </div>
  </div>

      <%# completer avec la photo et ajuster sur card_show_legend %>

      <%# coller un stickit dessus afin quelle suive le mouvement de la page  %>
      <div class="card-trip" data-controller="total-resa" data-price = "<%=@legend.price %>">
        <div class="card-trip-infos">
          <%= simple_form_for @reservation do |f| %>
            <div class="form-inputs">
              <h2>Louer cette légende !</h2>
              <%= f.input :starting_date,html5:true, input_html: {data:{total_resa_target:"start",action:"input->total-resa#calculate"} } %>
              <%= f.input :ending_date,html5:true, input_html: {data:{total_resa_target:"end",action:"input->total-resa#calculate"} } %>
              <%= f.hidden_field :legend_id, value: @legend.id %>
          <p data-total-resa-target="total"></p><br>
            </div>
              <div class="form-actions" id="btn-gradient" >
              <%= f.button :submit, "Book !"%>
            </div>
            <br>
            <div id="warning">Attention : l’application n’est pas juridiquement responsable en cas de destruction d’immeuble ou de l’univers.  </div>
          <% end %>
        </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/reservations/index.html.erb
<h2>Reservations Index</h2>

<ul>
  <% @reservations.each do |reservation| %>
    <li> ID:
      <%= link_to reservation.id, reservation_path(reservation) %>
    </li>
    <p>
    <%= reservation.legend.name %><br>
    <%= reservation.user.first_name %> <br>
    <%= reservation.user.last_name %> <br>
    <%= reservation.starting_date %><br>
    <%= reservation.ending_date %><br>
    </p>
  <% end %>
</ul>

app/views/reservations/new.html.erb
<%= simple_form_for @reservation do |f| %>
    <div class="form-inputs">
    <%= f.input :starting_date, as: :string, input_html: { type: 'date' } %>
    <%= f.input :ending_date, as: :string, input_html: { type: 'date' } %>
    <%= f.input :legend_id, collection: Legend.all.pluck(:name, :id), prompt: "Select a legend" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/reservations/show.html.erb
<h2>Reservation Show <%= @reservation.id %></h2>
<div>
  <ul>
    <li>Nom de l'objet: <strong><%= @reservation.legend.name %></strong></li>
    <li>Prenom du locataire <strong><%= @reservation.user.first_name %></strong></strong></strong></strong></li>
    <li>Nom du locataire: <strong><%= @reservation.user.last_name %></strong></strong></strong></li>
    <li>Debut de la reservation: <strong><%= @reservation.starting_date %></strong></strong></li>
    <li>Fin de la reservation: <strong><%= @reservation.ending_date %></strong></li>
    <li>
      <%= simple_form_for @reservation, url: update_status_reservation_path(@reservation), method: :patch, html: { id: 'status_form' } do |f| %>
        <div class="form-group" style="width: 150px">
          <%= f.input :status, collection: Reservation.statuses.keys.map { |status| [status.humanize, status] }, include_blank: false, selected: @reservation.status, input_html: { onchange: 'this.form.submit();' } %>
        </div>
      <% end %>
    </li>
    <li>
       <%= link_to "Destroy", @reservation, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
    </li>
  </ul>
</div>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <div class="navbar-left">
      <div class="icon-home">
        <%= link_to root_path do %>
          <i class="fa-solid fa-house home-button"></i>
        <% end %>
      </div>
    </div>

    <div class="navbar-middle">
      <h2>Legendary Objects</h2>
    </div>


    <div class="navbar-right">
      <div class="put-on-rent">
        <%= link_to "Mettre un objet en location", new_legend_path %>
      </div>


      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%#<%= link_to "Legend Objects", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= image_tag "user_profile_photo.png", class: "avatar", alt: "dropdown menu" %>
            </a>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "My Dashboard", user_path(current_user), class: "dropdown-item" %>
                <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
              </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>

    </div>
  </div>
</div>

app/views/shared/_search_bar.html.erb
<div class="row justify-content-center">
  <div class="col">
    <%= form_with url: legends_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Chercher un objet legend..."
        %>
      <button type="submit" class="search-button">
        <i class="fas fa-search"></i>
      </button>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class= "card-category header-dash">
  <h1> TABLEAU DE BORD </h1>
  <h2><%= @user.first_name.capitalize %> <%= @user.last_name.upcase %></h2>
  <h4><%= @user.email %></h4>
</div>

<div class="container-md">
  <div class="titles-dashboard">
    <h1 class="display-5"><%= "MES OBJETS DE LEGENDE" %></h1>
  </div>

    <div class="proprio-legends">
      <div>
        <% @legends.each do |legend| %>
          <div class= "cards-legend-container">
            <div>
              <%= link_to legend_path(legend), class: "card-legends-dashboard" do %>
                <%= cl_image_tag legend.photos.last.key, height: 300, width: 400, crop: :fill %>
                <div class= "card-legends-index-infos">
                  <h2><%= legend.name %></h2>
                  <p>
                    <%= legend.category %> <br>
                    <%= legend.description %>
                    <%= legend.price %> €/jour
                  </p>
                </div>
              <% end %>
              <div class="btn-delete-dashboard">
                <%= link_to legend_path(legend), data: {turbo_method: :delete, turbo_confirm: "Are you really really really sure ????"} do %>
                  <i class="fa-solid fa-trash" style="color: #000000;"></i>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>

      <div class= "cards-resa-dashboard">
        <div class="cards-resa-dashboard-infos">
          <% @legends.each do |legend| %>
            <% legend.reservations.each do |reservation| %>
              <%= cl_image_tag reservation.legend.photos.last.key %>
              <div>
                <p><%= reservation.legend.name %></p>
                <p>Du <%= reservation.starting_date %> Au <%= reservation.ending_date %></p>
                <% if reservation.status == "pending" %>
                  <div>
                    <%= link_to update_status_reservation_path(reservation, reservation: {status: "confirmed"}), data:{turbo_method: :patch} do %>
                      <i class="fa-solid fa-check"></i>
                    <%end %>
                    <%= link_to update_status_reservation_path(reservation, reservation: {status: "declined"}), data:{turbo_method: :patch} do %>
                      <i class="fa-solid fa-xmark" style="color: #ef0b0b;"></i>
                    <% end %>
                  </div>
                <% elsif reservation.status == "confirmed" %>
                  <p>Acceptée</p>
                <% elsif reservation.status == "declined" %>
                  <p>Déclinée</p>
                <% elsif reservation.status == "canceled" %>
                  <p>Annulée</p>
                <% end %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
  </div>






  <div class= "titles-dashboard">
    <h1 class="display-5"><%= "MES RESERVATIONS" %></h1>
  </div>
      <div class="proprio-legends">
          <% @reservations.each do |reservation| %>
            <div class= "cards-legend-container">
                <%= link_to legend_path(reservation.legend), class: "card-legends-dashboard" do %>
                <%= cl_image_tag reservation.legend.photos.last.key, height: 300, width: 400, crop: :fill %>
                <div class= "card-legends-index-infos">
                  <h2><%= reservation.legend.name %> (Propriétaire : <%= reservation.legend.user.first_name.capitalize %> <%= reservation.legend.user.last_name.capitalize %>)</h2>
                  <p> Demande du <%= reservation.starting_date %> au <%= reservation.ending_date %></p>
                  <% if reservation.status == "pending" %>
                  <p>Votre demande est : En attente</p>
                  <% elsif reservation.status == "confirmed" %>
                  <p>Votre demande est : Acceptée </p>
                  <% elsif reservation.status == "declined" %>
                  <p>Votre demande est : Refusée </p>
                  <% elsif reservation.status == "canceled" %>
                  <p>Votre demande est : Annulée </p>
                <% end %>
                </div>
                <% end %>
            </div>
          <% end %>
      </div>
</div>